services:
  - type: web
    name: crypto-index-api
    runtime: go
    region: singapore
    plan: free
    buildCommand: go build -o server ./cmd
    startCommand: ./server
    envVars:
      - key: GIN_MODE
        value: release
    healthCheckPath: /health

  - type: static
    name: crypto-index-frontend
    runtime: static
    region: singapore
    buildCommand: cd next-js && npm install && npm run build
    staticPublishPath: ./next-js/out
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production