services:
  - type: web
    name: crypto-index-api
    runtime: go
    region: singapore
    plan: free
    buildCommand: go build -o server ./cmd
    startCommand: ./server
    envVars:
      - key: GIN_MODE
        value: release
    healthCheckPath: /health
    env:
      - key: GO_VERSION
        value: 1.23

  - type: web
    name: crypto-index-frontend
    runtime: node
    region: singapore
    plan: free
    buildCommand: cd next-js && npm install && npm run build
    startCommand: cd next-js && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://crypto-index-api.onrender.com